services:
  mysql:
    image: mysql:8.4
    container_name: clinic-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clinic_root
      MYSQL_USER: clinic
      MYSQL_PASSWORD: clinic_password
    ports:
      - "3306:3306"
    volumes:
      - clinic_mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  clinic_mysql_data: