export enum CredentialType {
  MEDICAL_LICENSE = 'MEDICAL_LICENSE',
  DENTAL_LICENSE = 'DENTAL_LICENSE',
  BOARD_CERTIFICATION = 'BOARD_CERTIFICATION',
  DEGREE = 'DEGREE',
  TRAINING_CERTIFICATE = 'TRAINING_CERTIFICATE',
  OTHER = 'OTHER',
}
