export const WAITLIST_ENTRY_REPOSITORY = Symbol('WAITLIST_ENTRY_REPOSITORY');

export const WAITLIST_AVAILABILITY_CHECKER = Symbol(
    'WAITLIST_AVAILABILITY_CHECKER',
);

export const WAITLIST_APPOINTMENT_HOLD = Symbol(
    'WAITLIST_APPOINTMENT_HOLD',
);